include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_return: error
    dead_code: warning
    unused_import: error
    unused_local_variable: warning

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_fields: true
    require_trailing_commas: true
    avoid_relative_lib_imports: true
    unawaited_futures: true
    avoid_void_async: true
    avoid_empty_else: true
    camel_case_types: true
    file_names: true
    non_constant_identifier_names: true
    use_build_context_synchronously: true
    sort_constructors_first: true
    directives_ordering: true